export const productDetail={
	DEFAULT:{
		PRODUCT_DESC:"产品详情介绍正在推出，敬请期待!"//产品描述
	},
    SXT_photo:{
		PRODUCT_DESC:"人脸摄像头，在设备使用过程中根据业务需要调用摄像头，可拍摄客户面部高清视频图像，并输出不同类型、不同压缩比和像素的人像图片",//产品描述
		DEMOS:[{
			DEMO_NAME:"拍照--PJF.stm.SXT.takePhoto(args, callback)",//DEMO名称
			DEMO_CODE:"PJF.stm.SXT.takePhoto(<br/>	{<br/>		iIndex : 1, <br/>		imageType : 2, <br/>		iExpRate : 70, <br/>		iWidth : 640, <br/>		iHeight : 480, <br/>		pchPhotoPath : '/temp/test.jpg'}, <br/>	function(data) {<br/>		console.log(data.status);<br/>		console.log(data.Info.pbContent);<br/>	}<br/>);<br/>",//示例代码
			PRAMMETER_DESC:[{
				PARAM_NAME:"iIndex",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"摄像头编号 1:人脸摄像头；默认1",//说明
			},{
				PARAM_NAME:"imageType",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"图片保存类型，1-BMP格式，2-JPEG格式；默认2",//说明
			},{
				PARAM_NAME:"iExpRate",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"图片压缩比，该参数只在图片保存类型为2时有效，取值为0~100的整数如70；默认70",//说明
			},{
				PARAM_NAME:"iWidth",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"摄像头画面像素高度，px，默认640",//说明
			},{
				PARAM_NAME:"iHeight",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"摄像头画面像素高度，px，默认480",//说明
			},{
				PARAM_NAME:"pchPhotoPath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"图像文件所在绝对路径，包含文件名",//说明
			}],
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"..pbContent",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"图像的base64编码",//说明
					}]
				}
			]
		}]
	},
	SCA_scan:{
		PRODUCT_DESC:"扫描仪可以扫描不同纸张大小的单张扫描件，扫描后提供回收、回退扫描件的能力",//产品描述
		DEMOS:[{
			DEMO_NAME:"扫描--PJF.stm.SCA.scanOnePaper(args, callback)",//DEMO名称
			DEMO_CODE:"PJF.stm.SCA.scanOnePaper(<br/>	{<br/>		iIsA4Paper : 0, <br/>		pchFileSavePath : '/temp', <br/>		pchPrefixName : 'myFile', <br/>		iRecycleFlag : 0, <br/>		iCodeType : 0, <br/>		timeout : 30}, <br/>	function(data) {<br/>		console.log(data.pchCodeValue);<br/>		console.log(data.pchImageFileName);<br/>	}<br/>);<br/>",//示例代码
			PRAMMETER_DESC:[{
				PARAM_NAME:"iIsA4Paper",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"待扫描的原件是否是A4纸张，0-是，1-不是。默认0",//说明
			},{
				PARAM_NAME:"pchFileSavePath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"扫描得到影像文件存放目录的绝对路径",//说明
			},{
				PARAM_NAME:"pchPrefixName",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"指定扫描所得影像文件的文件名前缀",//说明
			},{
				PARAM_NAME:"iRecycleFlag",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"标识扫描完成后是否要回收原件。0-回退到入纸口；1-回收；2-留在扫描仪内部",//说明
			},{
				PARAM_NAME:"iCodeType",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"标识条码的种类。0：不需要识别；1：一维码；2：QR二维码；3：PDF147二维码；4：GM二维码",//说明
			},{
				PARAM_NAME:"timeout",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"超时时间，默认30，单位秒",//说明
			}],
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"..pchCodeValue",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"识别出来的条码数据。iCodeType为0时，返回空，否则返回识别出来的条码数据",//说明
					},{
						PARAM_NAME:"..pchImageFileName",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"返回影像文件的名称。带jpg后缀，只用返回正面影像的文件名即可，反面可解析获得",//说明
					}]
				}
			]
		},{
			DEMO_NAME:"回收/回退扫描件--PJF.stm.SCA.scanNextStep(args, callback)",//DEMO名称
			DEMO_CODE:"PJF.stm.SCA.scanOnePaper(<br/>	{<br/>		iIsA4Paper : 0, <br/>		pchFileSavePath : '/temp', <br/>		pchPrefixName : 'myFile', <br/>		iRecycleFlag : 0, <br/>		iCodeType : 0, <br/>		timeout : 30}, <br/>	function(data) {<br/>		console.log(data.pchCodeValue);<br/>		console.log(data.pchImageFileName);<br/>	}<br/>);<br/>",//示例代码
			PRAMMETER_DESC:[{
				PARAM_NAME:"iIsA4Paper",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"待扫描的原件是否是A4纸张，0-是，1-不是。默认0",//说明
			},{
				PARAM_NAME:"pchFileSavePath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"扫描得到影像文件存放目录的绝对路径",//说明
			},{
				PARAM_NAME:"pchPrefixName",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"指定扫描所得影像文件的文件名前缀",//说明
			},{
				PARAM_NAME:"iRecycleFlag",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"标识扫描完成后是否要回收原件。0-回退到入纸口；1-回收；2-留在扫描仪内部",//说明
			},{
				PARAM_NAME:"iCodeType",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"标识条码的种类。0：不需要识别；1：一维码；2：QR二维码；3：PDF147二维码；4：GM二维码",//说明
			},{
				PARAM_NAME:"timeout",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"超时时间，默认30，单位秒",//说明
			}],
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					}]
				}
			]
		},{
			DEMO_NAME:"结束扫描--PJF.stm.SCA.terminateScan(args, callback)",//DEMO名称
			DEMO_CODE:"PJF.stm.SCA.terminateScan(<br/>	{}, <br/>	function(data) {<br/>		console.log(data.status);<br/>	}<br/>);<br/>",//示例代码
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					}]
				}
			]
		}]
	},
	IdCard_read:{
		PRODUCT_DESC:"二代证阅读器，用于读取客户的身份证件信息",//产品描述
		DEMOS:[{
			DEMO_NAME:"读取信息--PJF.stm.IdCard. readCard (args, callback)",//DEMO名称
			DEMO_CODE:"PJF.stm.IdCard.readCard(<br/>	{<br/>		timeout : 30,<br/>		pchPhotoPath : '/temp/photo.jpg',<br/>		frontPhotoPath : '/temp/front.jpg',<br/>		backPhotoPath : '/temp/back.jpg'<br/>	},<br/>	function(data) {<br/>		console.log(data.info.pchInfo);<br/>	}<br/>);<br/>",//示例代码
			PRAMMETER_DESC:[{
				PARAM_NAME:"timeout",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"超时间隔，默认为30秒",//说明
			},{
				PARAM_NAME:"pchPhotoPath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"头像照片路径及文件名",//说明
			},{
				PARAM_NAME:"frontPhotoPath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"身份证扫描件正面路径及文件名",//说明
			},{
				PARAM_NAME:"backPhotoPath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"身份证扫描件反面路径及文件名",//说明
			}],
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchInfo",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"....name",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"姓名",//说明
					},{
						PARAM_NAME:"....sex",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"性别",//说明
					},{
						PARAM_NAME:"....nation",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"民族",//说明
					},{
						PARAM_NAME:"....birth",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"出生年月日",//说明
					},{
						PARAM_NAME:"....address",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"地址",//说明
					},{
						PARAM_NAME:"....identity",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"身份证号",//说明
					},{
						PARAM_NAME:"....issueOffice",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"发证机关",//说明
					},{
						PARAM_NAME:"....validDate",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"有效期限",//说明
					}]
				}
			]
		}]
	},
	HDP_print:{
		PRODUCT_DESC:"激光打印，预热打印机后，根据需要打印不同纸张大小的自定义文件",//产品描述
		DEMOS:[{
			DEMO_NAME:"预热打印机--PJF.stm.HDP.preparePrinter(args, CallBack)",//DEMO名称
			DEMO_CODE:"PJF.stm.HDP.preparePrinter(<br/>	{},<br/>	function(data) {<br/>		console.log(data.status);<br/>	}<br/>);<br/>",//示例代码
			PRAMMETER_DESC:[{
				PARAM_NAME:"iTotalPaperNum",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"预期打印张数",//说明
			},{
				PARAM_NAME:"iSlotType",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"指定需要使用的纸槽，默认为1<br/>1－1号纸槽（单联回单纸）<br/>2－2号纸槽（三联回单纸，尺寸同A4纸）<br/>3－3号纸槽（账页纸，尺寸同A4纸）<br/>4－4号纸槽（1/2 A4大小回单，尺寸同1/2 A4纸）",//说明
			},{
				PARAM_NAME:"iChapterType",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"否",//是否必填
				PARAM_DESC:"指定对应的盖章模式，默认为0<br/>0－不使用电子盖章<br/>1－1/3A4纸，单个章，横向<br/>2－A4纸3联单，3个章，纵向<br/>3－A4纸，单个章，纵向<br/>4－A4纸，单个章，横向<br/>5－1/2 A4纸回单，单个章，纵向",//说明
			},{
				PARAM_NAME:"pchChapterPos",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"盖章位置（单位：毫米），以进纸方向纸的边缘为一边，印章靠近进纸方向的印章边缘切线为另一条边，两条边之间的距离为盖章的位置。<br/>说明：当盖章模式为1,3,4,5时，传入形如“100”的参数，以指定单个章的位置；当盖章模式为2时，传入形如“100|0|200”的参数，以“|”进行分割成3个子参数，按顺序表示3个章不同的位置。当其中的某个子参数为“0”时，表示此位置不需要盖章。例如“100|0|200”，表示以进纸方向为起始，开始盖的一个章的位置为100毫米，第二个章不需要盖，第三个章的位置为200毫米",//说明
			},{
				PARAM_NAME:"iChapterNum",//参数名称
				PARAM_TYPE:"int",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"需要盖的章的总个数",//说明
			},{
				PARAM_NAME:"printFilePath",//参数名称
				PARAM_TYPE:"string",//参数类型
				PARAM_REQUIRE:"是",//是否必填
				PARAM_DESC:"指定要打印机的文件所在全路径，必须以txt,pdf,html为文件后缀，以打印对应格式文件",//说明
			}],
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					}]
				}
			]
		},{
			DEMO_NAME:"开始打印--PJF.stm.HDP.startPrintReceipt(args, CallBack)",//DEMO名称
			DEMO_CODE:"PJF.stm.HDP.preparePrinter(<br/>	{},<br/>	function(data) {<br/>		console.log(data.status);<br/>	}<br/>);<br/>",//示例代码
			CALLBACK:[
				{
					FUN_DESC:"回调函数",
					FUN_PARAM:[{
						PARAM_NAME:"status",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"调用结果 1-成功；0-失败",//说明
					},{
						PARAM_NAME:"errorCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"errorMsg",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"info",//参数名称
						PARAM_TYPE:"object",//参数类型
						PARAM_DESC:"对象",//说明
					},{
						PARAM_NAME:"..pchErrCode",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误码",//说明
					},{
						PARAM_NAME:"..pchError",//参数名称
						PARAM_TYPE:"string",//参数类型
						PARAM_DESC:"错误描述",//说明
					},{
						PARAM_NAME:"..printProgressData",//参数名称
						PARAM_TYPE:"int",//参数类型
						PARAM_DESC:"已打印张数",//说明
					}]
				}
			]
		}]
	}
}
